@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@customerId = {{create_customer.response.body.id}}

# @name create_user
POST {{baseURL}}/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@exemple.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
  "email": "john@exemple.com",
  "password": "12345678"
}

###

# @name user_profile
GET {{baseURL}}/users/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "john@exemple.com",
  "password": "12345678"
}

###

# @name create_customer
POST {{baseURL}}/customers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Eduardo",
  "email": "teste@teste.com",
  "phone": "12345678910",
  "sector": "TI"
}

###

# @name edit_customer
PUT {{baseURL}}/customers/{{customerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Eduardo",
  "email": "teste@teste.com",
  "phone": "12345678910",
  "sector": "TI"
}

###

# @name list_service_with_customer_id
GET {{baseURL}}/services?customerId={{customerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name list_all_user_services
GET {{baseURL}}/services/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

